kind: Service
apiVersion: v1
metadata:
  name: springboot-k8s-mysql
spec:
  type: LoadBalancer
  selector:
    app: springboot-k8s-mysql
  ports:
  - port: 80
    targetPort: 8080      

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: springboot-k8s-mysql
spec:                
  selector:         
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 1        
  template:
    metadata:
      labels:        
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-k8s-mysql
          image: gcr.io/jenkins-276120/springboot-k8s-mysql:latest
          ports:
            - containerPort: 8080                
          env:   # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: mysql-config  # name of configMap
                key: MYSQL_DATABASE_URL
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_DATABASE
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: mysql-secret # Secret Name
                key: MYSQL_USER
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD     
        